name: RFC action

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  rfc-action:
    name: Handle an RFC-relate command in a RFC proposal PR
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rfc') }}
    runs-on: ubuntu-latest
    steps:
      - uses: paritytech/rfc-action@rzadp/link-to-logs
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
